name: Adapter Integration Tests

on:
  workflow_dispatch:

# explicitly turn off permissions for `GITHUB_TOKEN`
permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  test-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository (non-PR)
        uses: actions/checkout@v3
        with:
          persist-credentials: false
